package erp.hr.modules;


import erp.hr.views.HrEmplInfoViewImpl;


import erp.hr.views.InvInventoryViewImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 25 15:01:38 AST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HR_AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HR_AppModuleImpl() {
    }

    /**
     * Container's getter for HrEmplAddressView1.
     * @return HrEmplAddressView1
     */
    public ViewObjectImpl getHrEmplAddressView1() {
        return (ViewObjectImpl) findViewObject("HrEmplAddressView1");
    }

    /**
     * Container's getter for HrEmplEmailView1.
     * @return HrEmplEmailView1
     */
    public ViewObjectImpl getHrEmplEmailView1() {
        return (ViewObjectImpl) findViewObject("HrEmplEmailView1");
    }

    /**
     * Container's getter for HrEmplInfoView1.
     * @return HrEmplInfoView1
     */
    public HrEmplInfoViewImpl getHrEmplInfoView1() {
        return (HrEmplInfoViewImpl) findViewObject("HrEmplInfoView1");
    }

    /**
     * Container's getter for HrEmplPhoneView1.
     * @return HrEmplPhoneView1
     */
    public ViewObjectImpl getHrEmplPhoneView1() {
        return (ViewObjectImpl) findViewObject("HrEmplPhoneView1");
    }

    /**
     * Container's getter for HrEmplEmailView2.
     * @return HrEmplEmailView2
     */
    public ViewObjectImpl getHrEmplEmailView2() {
        return (ViewObjectImpl) findViewObject("HrEmplEmailView2");
    }

    /**
     * Container's getter for HrEmplAddressView2.
     * @return HrEmplAddressView2
     */
    public ViewObjectImpl getHrEmplAddressView2() {
        return (ViewObjectImpl) findViewObject("HrEmplAddressView2");
    }

    /**
     * Container's getter for HrEmplPhoneView2.
     * @return HrEmplPhoneView2
     */
    public ViewObjectImpl getHrEmplPhoneView2() {
        return (ViewObjectImpl) findViewObject("HrEmplPhoneView2");
    }

    /**
     * Container's getter for HrLookupTblView1.
     * @return HrLookupTblView1
     */
    public ViewObjectImpl getHrLookupTblView1() {
        return (ViewObjectImpl) findViewObject("HrLookupTblView1");
    }

    /**
     * Container's getter for HrLookupTblView2.
     * @return HrLookupTblView2
     */
    public ViewObjectImpl getHrLookupTblView2() {
        return (ViewObjectImpl) findViewObject("HrLookupTblView2");
    }

    /**
     * Container's getter for HrLookupTblView3.
     * @return HrLookupTblView3
     */
    public ViewObjectImpl getHrLookupTblView3() {
        return (ViewObjectImpl) findViewObject("HrLookupTblView3");
    }

    /**
     * Container's getter for HrEmplBankInfoView1.
     * @return HrEmplBankInfoView1
     */
    public ViewObjectImpl getHrEmplBankInfoView1() {
        return (ViewObjectImpl) findViewObject("HrEmplBankInfoView1");
    }


    /**
     * Container's getter for HrEmplJobView2.
     * @return HrEmplJobView2
     */
    public ViewObjectImpl getHrEmplJobView2() {
        return (ViewObjectImpl) findViewObject("HrEmplJobView2");
    }

    /**
     * Container's getter for HrEmplBankInfoView2.
     * @return HrEmplBankInfoView2
     */
    public ViewObjectImpl getHrEmplBankInfoView2() {
        return (ViewObjectImpl) findViewObject("HrEmplBankInfoView2");
    }

    /**
     * Container's getter for HrEmplLeavesView1.
     * @return HrEmplLeavesView1
     */
    public ViewObjectImpl getHrEmplLeavesView1() {
        return (ViewObjectImpl) findViewObject("HrEmplLeavesView1");
    }

    /**
     * Container's getter for HrEmplLoanView1.
     * @return HrEmplLoanView1
     */
    public ViewObjectImpl getHrEmplLoanView1() {
        return (ViewObjectImpl) findViewObject("HrEmplLoanView1");
    }


    /**
     * Container's getter for HrEmplLeavesView2.
     * @return HrEmplLeavesView2
     */
    public ViewObjectImpl getHrEmplLeavesView2() {
        return (ViewObjectImpl) findViewObject("HrEmplLeavesView2");
    }

    /**
     * Container's getter for HrEmplLoanView2.
     * @return HrEmplLoanView2
     */
    public ViewObjectImpl getHrEmplLoanView2() {
        return (ViewObjectImpl) findViewObject("HrEmplLoanView2");
    }


    /**
     * Container's getter for HrEmplAppraisalView1.
     * @return HrEmplAppraisalView1
     */
    public ViewObjectImpl getHrEmplAppraisalView1() {
        return (ViewObjectImpl) findViewObject("HrEmplAppraisalView1");
    }

    /**
     * Container's getter for HrEmplBenefitsView1.
     * @return HrEmplBenefitsView1
     */
    public ViewObjectImpl getHrEmplBenefitsView1() {
        return (ViewObjectImpl) findViewObject("HrEmplBenefitsView1");
    }

    /**
     * Container's getter for HrEmplCompensationsView1.
     * @return HrEmplCompensationsView1
     */
    public ViewObjectImpl getHrEmplCompensationsView1() {
        return (ViewObjectImpl) findViewObject("HrEmplCompensationsView1");
    }

    /**
     * Container's getter for HrEmplBenefitsView2.
     * @return HrEmplBenefitsView2
     */
    public ViewObjectImpl getHrEmplBenefitsView2() {
        return (ViewObjectImpl) findViewObject("HrEmplBenefitsView2");
    }

    /**
     * Container's getter for HrEmplCompensationsView2.
     * @return HrEmplCompensationsView2
     */
    public ViewObjectImpl getHrEmplCompensationsView2() {
        return (ViewObjectImpl) findViewObject("HrEmplCompensationsView2");
    }

    /**
     * Container's getter for HrEmplAppraisalView2.
     * @return HrEmplAppraisalView2
     */
    public ViewObjectImpl getHrEmplAppraisalView2() {
        return (ViewObjectImpl) findViewObject("HrEmplAppraisalView2");
    }

    /**
     * Container's getter for HrEmplDependentsView1.
     * @return HrEmplDependentsView1
     */
    public ViewObjectImpl getHrEmplDependentsView1() {
        return (ViewObjectImpl) findViewObject("HrEmplDependentsView1");
    }

    /**
     * Container's getter for HrEmplEducationView1.
     * @return HrEmplEducationView1
     */
    public ViewObjectImpl getHrEmplEducationView1() {
        return (ViewObjectImpl) findViewObject("HrEmplEducationView1");
    }

    /**
     * Container's getter for HrEmplEmergencyContactsView1.
     * @return HrEmplEmergencyContactsView1
     */
    public ViewObjectImpl getHrEmplEmergencyContactsView1() {
        return (ViewObjectImpl) findViewObject("HrEmplEmergencyContactsView1");
    }

    /**
     * Container's getter for HrEmplExperienceView1.
     * @return HrEmplExperienceView1
     */
    public ViewObjectImpl getHrEmplExperienceView1() {
        return (ViewObjectImpl) findViewObject("HrEmplExperienceView1");
    }

    /**
     * Container's getter for HrInsuranceBeneficiariesView1.
     * @return HrInsuranceBeneficiariesView1
     */
    public ViewObjectImpl getHrInsuranceBeneficiariesView1() {
        return (ViewObjectImpl) findViewObject("HrInsuranceBeneficiariesView1");
    }

    /**
     * Container's getter for HrEmplDependentsView2.
     * @return HrEmplDependentsView2
     */
    public ViewObjectImpl getHrEmplDependentsView2() {
        return (ViewObjectImpl) findViewObject("HrEmplDependentsView2");
    }

    /**
     * Container's getter for HrEmplEducationView2.
     * @return HrEmplEducationView2
     */
    public ViewObjectImpl getHrEmplEducationView2() {
        return (ViewObjectImpl) findViewObject("HrEmplEducationView2");
    }

    /**
     * Container's getter for HrEmplEmergencyContactsView2.
     * @return HrEmplEmergencyContactsView2
     */
    public ViewObjectImpl getHrEmplEmergencyContactsView2() {
        return (ViewObjectImpl) findViewObject("HrEmplEmergencyContactsView2");
    }

    /**
     * Container's getter for HrEmplExperienceView2.
     * @return HrEmplExperienceView2
     */
    public ViewObjectImpl getHrEmplExperienceView2() {
        return (ViewObjectImpl) findViewObject("HrEmplExperienceView2");
    }

    /**
     * Container's getter for HrInsuranceBeneficiariesView2.
     * @return HrInsuranceBeneficiariesView2
     */
    public ViewObjectImpl getHrInsuranceBeneficiariesView2() {
        return (ViewObjectImpl) findViewObject("HrInsuranceBeneficiariesView2");
    }

    /**
     * Container's getter for HrCompanyPropertiesView1.
     * @return HrCompanyPropertiesView1
     */
    public ViewObjectImpl getHrCompanyPropertiesView1() {
        return (ViewObjectImpl) findViewObject("HrCompanyPropertiesView1");
    }

    /**
     * Container's getter for HrEmplPassportView1.
     * @return HrEmplPassportView1
     */
    public ViewObjectImpl getHrEmplPassportView1() {
        return (ViewObjectImpl) findViewObject("HrEmplPassportView1");
    }

    /**
     * Container's getter for HrResidencePermitView1.
     * @return HrResidencePermitView1
     */
    public ViewObjectImpl getHrResidencePermitView1() {
        return (ViewObjectImpl) findViewObject("HrResidencePermitView1");
    }

    /**
     * Container's getter for HrCompanyPropertiesView2.
     * @return HrCompanyPropertiesView2
     */
    public ViewObjectImpl getHrCompanyPropertiesView2() {
        return (ViewObjectImpl) findViewObject("HrCompanyPropertiesView2");
    }

    /**
     * Container's getter for HrEmplPassportView2.
     * @return HrEmplPassportView2
     */
    public ViewObjectImpl getHrEmplPassportView2() {
        return (ViewObjectImpl) findViewObject("HrEmplPassportView2");
    }

    /**
     * Container's getter for HrResidencePermitView2.
     * @return HrResidencePermitView2
     */
    public ViewObjectImpl getHrResidencePermitView2() {
        return (ViewObjectImpl) findViewObject("HrResidencePermitView2");
    }

    /**
     * Container's getter for EmplEmailLink1.
     * @return EmplEmailLink1
     */
    public ViewLinkImpl getEmplEmailLink1() {
        return (ViewLinkImpl) findViewLink("EmplEmailLink1");
    }

    /**
     * Container's getter for EmplAddressLink1.
     * @return EmplAddressLink1
     */
    public ViewLinkImpl getEmplAddressLink1() {
        return (ViewLinkImpl) findViewLink("EmplAddressLink1");
    }

    /**
     * Container's getter for EmplPhoneLink1.
     * @return EmplPhoneLink1
     */
    public ViewLinkImpl getEmplPhoneLink1() {
        return (ViewLinkImpl) findViewLink("EmplPhoneLink1");
    }

    /**
     * Container's getter for empl_JobViewLink1.
     * @return empl_JobViewLink1
     */
    public ViewLinkImpl getempl_JobViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_JobViewLink1");
    }

    /**
     * Container's getter for empl_BankViewLink1.
     * @return empl_BankViewLink1
     */
    public ViewLinkImpl getempl_BankViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_BankViewLink1");
    }

    /**
     * Container's getter for empl_leavesViewLink1.
     * @return empl_leavesViewLink1
     */
    public ViewLinkImpl getempl_leavesViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_leavesViewLink1");
    }

    /**
     * Container's getter for empl_LoansViewLink1.
     * @return empl_LoansViewLink1
     */
    public ViewLinkImpl getempl_LoansViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_LoansViewLink1");
    }


    /**
     * Container's getter for empl_BenefitsViewLink1.
     * @return empl_BenefitsViewLink1
     */
    public ViewLinkImpl getempl_BenefitsViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_BenefitsViewLink1");
    }

    /**
     * Container's getter for empl_CompensationsViewLink1.
     * @return empl_CompensationsViewLink1
     */
    public ViewLinkImpl getempl_CompensationsViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_CompensationsViewLink1");
    }

    /**
     * Container's getter for empl_AppraisalViewLink1.
     * @return empl_AppraisalViewLink1
     */
    public ViewLinkImpl getempl_AppraisalViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_AppraisalViewLink1");
    }

    /**
     * Container's getter for empl_DepenentsViewLink1.
     * @return empl_DepenentsViewLink1
     */
    public ViewLinkImpl getempl_DepenentsViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_DepenentsViewLink1");
    }

    /**
     * Container's getter for empl_EducationViewLink1.
     * @return empl_EducationViewLink1
     */
    public ViewLinkImpl getempl_EducationViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_EducationViewLink1");
    }

    /**
     * Container's getter for empl_emergencyContactsViewLink1.
     * @return empl_emergencyContactsViewLink1
     */
    public ViewLinkImpl getempl_emergencyContactsViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_emergencyContactsViewLink1");
    }

    /**
     * Container's getter for empl_ExperienceViewLink1.
     * @return empl_ExperienceViewLink1
     */
    public ViewLinkImpl getempl_ExperienceViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_ExperienceViewLink1");
    }

    /**
     * Container's getter for empl_lifeInsuranceBeneficieresViewLink1.
     * @return empl_lifeInsuranceBeneficieresViewLink1
     */
    public ViewLinkImpl getempl_lifeInsuranceBeneficieresViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_lifeInsuranceBeneficieresViewLink1");
    }

    /**
     * Container's getter for empl_CompanyPropertiesViewLink1.
     * @return empl_CompanyPropertiesViewLink1
     */
    public ViewLinkImpl getempl_CompanyPropertiesViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_CompanyPropertiesViewLink1");
    }

    /**
     * Container's getter for empl_PassportViewLink1.
     * @return empl_PassportViewLink1
     */
    public ViewLinkImpl getempl_PassportViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_PassportViewLink1");
    }

    /**
     * Container's getter for empl_ResidencePermitViewLink1.
     * @return empl_ResidencePermitViewLink1
     */
    public ViewLinkImpl getempl_ResidencePermitViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_ResidencePermitViewLink1");
    }

    /**
     * Container's getter for HrNewjobsInfoView1.
     * @return HrNewjobsInfoView1
     */
    public ViewObjectImpl getHrNewjobsInfoView1() {
        return (ViewObjectImpl) findViewObject("HrNewjobsInfoView1");
    }

    /**
     * Container's getter for HrDepartmentsView1.
     * @return HrDepartmentsView1
     */
    public ViewObjectImpl getHrDepartmentsView1() {
        return (ViewObjectImpl) findViewObject("HrDepartmentsView1");
    }

    /**
     * Container's getter for HrDirectoresView1.
     * @return HrDirectoresView1
     */
    public ViewObjectImpl getHrDirectoresView1() {
        return (ViewObjectImpl) findViewObject("HrDirectoresView1");
    }


    /**
     * Container's getter for HrDepartmentsView2.
     * @return HrDepartmentsView2
     */
    public ViewObjectImpl getHrDepartmentsView2() {
        return (ViewObjectImpl) findViewObject("HrDepartmentsView2");
    }

    /**
     * Container's getter for Directorate_DepartmentViewLink1.
     * @return Directorate_DepartmentViewLink1
     */
    public ViewLinkImpl getDirectorate_DepartmentViewLink1() {
        return (ViewLinkImpl) findViewLink("Directorate_DepartmentViewLink1");
    }

    /**
     * Container's getter for HrGradeAttributesView1.
     * @return HrGradeAttributesView1
     */
    public ViewObjectImpl getHrGradeAttributesView1() {
        return (ViewObjectImpl) findViewObject("HrGradeAttributesView1");
    }

    /**
     * Container's getter for HrGradesView1.
     * @return HrGradesView1
     */
    public ViewObjectImpl getHrGradesView1() {
        return (ViewObjectImpl) findViewObject("HrGradesView1");
    }


    /**
     * Container's getter for HrGradeAttributesView2.
     * @return HrGradeAttributesView2
     */
    public ViewObjectImpl getHrGradeAttributesView2() {
        return (ViewObjectImpl) findViewObject("HrGradeAttributesView2");
    }

    /**
     * Container's getter for Grade_ViewLink1.
     * @return Grade_ViewLink1
     */
    public ViewLinkImpl getGrade_ViewLink1() {
        return (ViewLinkImpl) findViewLink("Grade_ViewLink1");
    }

    /**
     * Container's getter for Search_lookupView1.
     * @return Search_lookupView1
     */
    public ViewObjectImpl getSearch_lookupView1() {
        return (ViewObjectImpl) findViewObject("Search_lookupView1");
    }

    /**
     * Container's getter for HrDentalPlanView1.
     * @return HrDentalPlanView1
     */
    public ViewObjectImpl getHrDentalPlanView1() {
        return (ViewObjectImpl) findViewObject("HrDentalPlanView1");
    }

    /**
     * Container's getter for HrHealthPlanView1.
     * @return HrHealthPlanView1
     */
    public ViewObjectImpl getHrHealthPlanView1() {
        return (ViewObjectImpl) findViewObject("HrHealthPlanView1");
    }


    /**
     * Container's getter for HrAppraisalsView1.
     * @return HrAppraisalsView1
     */
    public ViewObjectImpl getHrAppraisalsView1() {
        return (ViewObjectImpl) findViewObject("HrAppraisalsView1");
    }

    /**
     * Container's getter for HrAppraisalYearView1.
     * @return HrAppraisalYearView1
     */
    public ViewObjectImpl getHrAppraisalYearView1() {
        return (ViewObjectImpl) findViewObject("HrAppraisalYearView1");
    }


    /**
     * Container's getter for HrAppraisalYearView3.
     * @return HrAppraisalYearView3
     */
    public ViewObjectImpl getHrAppraisalYearView3() {
        return (ViewObjectImpl) findViewObject("HrAppraisalYearView3");
    }

    /**
     * Container's getter for EmployeJob_AppraisalYearViewLink1.
     * @return EmployeJob_AppraisalYearViewLink1
     */
    public ViewLinkImpl getEmployeJob_AppraisalYearViewLink1() {
        return (ViewLinkImpl) findViewLink("EmployeJob_AppraisalYearViewLink1");
    }


    /**
     * Container's getter for HrAppraisalsView4.
     * @return HrAppraisalsView4
     */
    public ViewObjectImpl getHrAppraisalsView4() {
        return (ViewObjectImpl) findViewObject("HrAppraisalsView4");
    }

    /**
     * Container's getter for Appraisal_AppraisalYearLink3.
     * @return Appraisal_AppraisalYearLink3
     */
    public ViewLinkImpl getAppraisal_AppraisalYearLink3() {
        return (ViewLinkImpl) findViewLink("Appraisal_AppraisalYearLink3");
    }


    /**
     * Container's getter for HrTrainingsView1.
     * @return HrTrainingsView1
     */
    public ViewObjectImpl getHrTrainingsView1() {
        return (ViewObjectImpl) findViewObject("HrTrainingsView1");
    }


    /**
     * Container's getter for HrEmplInfoView2.
     * @return HrEmplInfoView2
     */
    public HrEmplInfoViewImpl getHrEmplInfoView2() {
        return (HrEmplInfoViewImpl) findViewObject("HrEmplInfoView2");
    }

    /**
     * Container's getter for Appraisal_EmplViewLink1.
     * @return Appraisal_EmplViewLink1
     */
    public ViewLinkImpl getAppraisal_EmplViewLink1() {
        return (ViewLinkImpl) findViewLink("Appraisal_EmplViewLink1");
    }

    /**
     * Container's getter for HrEmplTrainingsView3.
     * @return HrEmplTrainingsView3
     */
    public ViewObjectImpl getHrEmplTrainingsView3() {
        return (ViewObjectImpl) findViewObject("HrEmplTrainingsView3");
    }

    /**
     * Container's getter for empl_TrainingsViewLink2.
     * @return empl_TrainingsViewLink2
     */
    public ViewLinkImpl getempl_TrainingsViewLink2() {
        return (ViewLinkImpl) findViewLink("empl_TrainingsViewLink2");
    }

    /**
     * Container's getter for HrEmplTrainingsView1.
     * @return HrEmplTrainingsView1
     */
    public ViewObjectImpl getHrEmplTrainingsView1() {
        return (ViewObjectImpl) findViewObject("HrEmplTrainingsView1");
    }


    /**
     * Container's getter for HrEmplTrainingsView2.
     * @return HrEmplTrainingsView2
     */
    public ViewObjectImpl getHrEmplTrainingsView2() {
        return (ViewObjectImpl) findViewObject("HrEmplTrainingsView2");
    }

    /**
     * Container's getter for empl_TrainingsViewLink1.
     * @return empl_TrainingsViewLink1
     */
    public ViewLinkImpl getempl_TrainingsViewLink1() {
        return (ViewLinkImpl) findViewLink("empl_TrainingsViewLink1");
    }

    /**
     * Container's getter for HrEmplInfoView3.
     * @return HrEmplInfoView3
     */
    public HrEmplInfoViewImpl getHrEmplInfoView3() {
        return (HrEmplInfoViewImpl) findViewObject("HrEmplInfoView3");
    }

    /**
     * Container's getter for AppraisalYear_EMPLsViewLink1.
     * @return AppraisalYear_EMPLsViewLink1
     */
    public ViewLinkImpl getAppraisalYear_EMPLsViewLink1() {
        return (ViewLinkImpl) findViewLink("AppraisalYear_EMPLsViewLink1");
    }

    /**
     * Container's getter for HrEmplAppraisalView3.
     * @return HrEmplAppraisalView3
     */
    public ViewObjectImpl getHrEmplAppraisalView3() {
        return (ViewObjectImpl) findViewObject("HrEmplAppraisalView3");
    }

    /**
     * Container's getter for empl_AppraisalViewLink2.
     * @return empl_AppraisalViewLink2
     */
    public ViewLinkImpl getempl_AppraisalViewLink2() {
        return (ViewLinkImpl) findViewLink("empl_AppraisalViewLink2");
    }


    /**
     * Container's getter for InvOrdersView1.
     * @return InvOrdersView1
     */
    public ViewObjectImpl getInvOrdersView1() {
        return (ViewObjectImpl) findViewObject("InvOrdersView1");
    }

    /**
     * Container's getter for InvTransfersView1.
     * @return InvTransfersView1
     */
    public ViewObjectImpl getInvTransfersView1() {
        return (ViewObjectImpl) findViewObject("InvTransfersView1");
    }


    /**
     * Container's getter for InvCustomersView1.
     * @return InvCustomersView1
     */
    public ViewObjectImpl getInvCustomersView1() {
        return (ViewObjectImpl) findViewObject("InvCustomersView1");
    }


    /**
     * Container's getter for InvVendorsView1.
     * @return InvVendorsView1
     */
    public ViewObjectImpl getInvVendorsView1() {
        return (ViewObjectImpl) findViewObject("InvVendorsView1");
    }


    /**
     * Container's getter for InvSalesView1.
     * @return InvSalesView1
     */
    public ViewObjectImpl getInvSalesView1() {
        return (ViewObjectImpl) findViewObject("InvSalesView1");
    }


    /**
     * Container's getter for FinPaymentsView2.
     * @return FinPaymentsView2
     */
    public ViewObjectImpl getFinPaymentsView2() {
        return (ViewObjectImpl) findViewObject("FinPaymentsView2");
    }

    /**
     * Container's getter for Sale_PaymentviewLink1.
     * @return Sale_PaymentviewLink1
     */
    public ViewLinkImpl getSale_PaymentviewLink1() {
        return (ViewLinkImpl) findViewLink("Sale_PaymentviewLink1");
    }


    /**
     * Container's getter for FinPayrollView1.
     * @return FinPayrollView1
     */
    public ViewObjectImpl getFinPayrollView1() {
        return (ViewObjectImpl) findViewObject("FinPayrollView1");
    }

    /**
     * Container's getter for FinTransactionsView1.
     * @return FinTransactionsView1
     */
    public ViewObjectImpl getFinTransactionsView1() {
        return (ViewObjectImpl) findViewObject("FinTransactionsView1");
    }


    /**
     * Container's getter for FinSettlePaymentsView1.
     * @return FinSettlePaymentsView1
     */
    public ViewObjectImpl getFinSettlePaymentsView1() {
        return (ViewObjectImpl) findViewObject("FinSettlePaymentsView1");
    }


    /**
     * Container's getter for FinReconcileView1.
     * @return FinReconcileView1
     */
    public ViewObjectImpl getFinReconcileView1() {
        return (ViewObjectImpl) findViewObject("FinReconcileView1");
    }

    /**
     * Container's getter for FinChartOfAccountsView1.
     * @return FinChartOfAccountsView1
     */
    public ViewObjectImpl getFinChartOfAccountsView1() {
        return (ViewObjectImpl) findViewObject("FinChartOfAccountsView1");
    }


    /**
     * Container's getter for InvCustomersView3.
     * @return InvCustomersView3
     */
    public ViewObjectImpl getInvCustomersView3() {
        return (ViewObjectImpl) findViewObject("InvCustomersView3");
    }

    /**
     * Container's getter for sale_customerViewLink2.
     * @return sale_customerViewLink2
     */
    public ViewLinkImpl getsale_customerViewLink2() {
        return (ViewLinkImpl) findViewLink("sale_customerViewLink2");
    }


    /**
     * Container's getter for FinPaymentsView1.
     * @return FinPaymentsView1
     */
    public ViewObjectImpl getFinPaymentsView1() {
        return (ViewObjectImpl) findViewObject("FinPaymentsView1");
    }

    /**
     * Container's getter for Order_PaymentViewLink1.
     * @return Order_PaymentViewLink1
     */
    public ViewLinkImpl getOrder_PaymentViewLink1() {
        return (ViewLinkImpl) findViewLink("Order_PaymentViewLink1");
    }


    /**
     * Container's getter for InvVendorsView2.
     * @return InvVendorsView2
     */
    public ViewObjectImpl getInvVendorsView2() {
        return (ViewObjectImpl) findViewObject("InvVendorsView2");
    }

    /**
     * Container's getter for order_supplierViewLink1.
     * @return order_supplierViewLink1
     */
    public ViewLinkImpl getorder_supplierViewLink1() {
        return (ViewLinkImpl) findViewLink("order_supplierViewLink1");
    }


    /**
     * Container's getter for InvSaleItemsView1.
     * @return InvSaleItemsView1
     */
    public ViewObjectImpl getInvSaleItemsView1() {
        return (ViewObjectImpl) findViewObject("InvSaleItemsView1");
    }

    /**
     * Container's getter for sales_salesItemViewLink1.
     * @return sales_salesItemViewLink1
     */
    public ViewLinkImpl getsales_salesItemViewLink1() {
        return (ViewLinkImpl) findViewLink("sales_salesItemViewLink1");
    }

    /**
     * Container's getter for InvOrderedItemsView1.
     * @return InvOrderedItemsView1
     */
    public ViewObjectImpl getInvOrderedItemsView1() {
        return (ViewObjectImpl) findViewObject("InvOrderedItemsView1");
    }

    /**
     * Container's getter for POs_POItemsViewLink1.
     * @return POs_POItemsViewLink1
     */
    public ViewLinkImpl getPOs_POItemsViewLink1() {
        return (ViewLinkImpl) findViewLink("POs_POItemsViewLink1");
    }


    /**
     * Container's getter for InvInventoryView1.
     * @return InvInventoryView1
     */
    public ViewObjectImpl getInvInventoryView1() {
        return (ViewObjectImpl) findViewObject("InvInventoryView1");
    }

    /**
     * Container's getter for InvSalesView2.
     * @return InvSalesView2
     */
    public ViewObjectImpl getInvSalesView2() {
        return (ViewObjectImpl) findViewObject("InvSalesView2");
    }

    /**
     * Container's getter for Inventory_SaleViewLink1.
     * @return Inventory_SaleViewLink1
     */
    public ViewLinkImpl getInventory_SaleViewLink1() {
        return (ViewLinkImpl) findViewLink("Inventory_SaleViewLink1");
    }

    /**
     * Container's getter for InvTransfersView2.
     * @return InvTransfersView2
     */
    public ViewObjectImpl getInvTransfersView2() {
        return (ViewObjectImpl) findViewObject("InvTransfersView2");
    }

    /**
     * Container's getter for Item_transfersViewLink1.
     * @return Item_transfersViewLink1
     */
    public ViewLinkImpl getItem_transfersViewLink1() {
        return (ViewLinkImpl) findViewLink("Item_transfersViewLink1");
    }


    /**
     * Container's getter for InvInventoryView2.
     * @return InvInventoryView2
     */
    public InvInventoryViewImpl getInvInventoryView2() {
        return (InvInventoryViewImpl) findViewObject("InvInventoryView2");
    }

    /**
     * Container's getter for mainSaleitems_inventoryViewLink1.
     * @return mainSaleitems_inventoryViewLink1
     */
    public ViewLinkImpl getmainSaleitems_inventoryViewLink1() {
        return (ViewLinkImpl) findViewLink("mainSaleitems_inventoryViewLink1");
    }

    /**
     * Container's getter for HrEmplJobView1.
     * @return HrEmplJobView1
     */
    public ViewObjectImpl getHrEmplJobView1() {
        return (ViewObjectImpl) findViewObject("HrEmplJobView1");
    }

    /**
     * Container's getter for HrEmplAppraisalView4.
     * @return HrEmplAppraisalView4
     */
    public ViewObjectImpl getHrEmplAppraisalView4() {
        return (ViewObjectImpl) findViewObject("HrEmplAppraisalView4");
    }

    /**
     * Container's getter for emplJob_EmplAppraisalViewLink.
     * @return emplJob_EmplAppraisalViewLink
     */
    public ViewLinkImpl getemplJob_EmplAppraisalViewLink() {
        return (ViewLinkImpl) findViewLink("emplJob_EmplAppraisalViewLink");
    }

    /**
     * Container's getter for HrEmplAppraisalView5.
     * @return HrEmplAppraisalView5
     */
    public ViewObjectImpl getHrEmplAppraisalView5() {
        return (ViewObjectImpl) findViewObject("HrEmplAppraisalView5");
    }

    /**
     * Container's getter for emplJob_EmplAppraisalViewLink1.
     * @return emplJob_EmplAppraisalViewLink1
     */
    public ViewLinkImpl getemplJob_EmplAppraisalViewLink1() {
        return (ViewLinkImpl) findViewLink("emplJob_EmplAppraisalViewLink1");
    }

    /**
     * Container's getter for HrCourseView1.
     * @return HrCourseView1
     */
    public ViewObjectImpl getHrCourseView1() {
        return (ViewObjectImpl) findViewObject("HrCourseView1");
    }


    /**
     * Container's getter for FinChartOfAccountsView2.
     * @return FinChartOfAccountsView2
     */
    public ViewObjectImpl getFinChartOfAccountsView2() {
        return (ViewObjectImpl) findViewObject("FinChartOfAccountsView2");
    }

    /**
     * Container's getter for Payment_GLAccountsViewLink1.
     * @return Payment_GLAccountsViewLink1
     */
    public ViewLinkImpl getPayment_GLAccountsViewLink1() {
        return (ViewLinkImpl) findViewLink("Payment_GLAccountsViewLink1");
    }


    /**
     * Container's getter for HrEmplJobView3.
     * @return HrEmplJobView3
     */
    public ViewObjectImpl getHrEmplJobView3() {
        return (ViewObjectImpl) findViewObject("HrEmplJobView3");
    }

    /**
     * Container's getter for Appraisal_EmpJobViewLink1.
     * @return Appraisal_EmpJobViewLink1
     */
    public ViewLinkImpl getAppraisal_EmpJobViewLink1() {
        return (ViewLinkImpl) findViewLink("Appraisal_EmpJobViewLink1");
    }


    /**
     * Container's getter for HrAppraisalsView2.
     * @return HrAppraisalsView2
     */
    public ViewObjectImpl getHrAppraisalsView2() {
        return (ViewObjectImpl) findViewObject("HrAppraisalsView2");
    }

    /**
     * Container's getter for empJob_AppraisalViewLink1.
     * @return empJob_AppraisalViewLink1
     */
    public ViewLinkImpl getempJob_AppraisalViewLink1() {
        return (ViewLinkImpl) findViewLink("empJob_AppraisalViewLink1");
    }
}

