package erp.inv.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 19 11:08:23 AST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvInventoryViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public InvInventoryViewImpl() {
    }
}

